web-app-asp-net-mvc-export-xml/Models/Entities/Lesson.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web_app_asp_net_mvc_export_xml.Extensions;
using web_app_asp_net_mvc_export_xml.Models.Attributes;

namespace web_app_asp_net_mvc_export_xml.Models
{
    public class Lesson
    {
        /// <summary>
        /// Id
        /// </summary> 
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Порядковый номер пары в расписании
        /// </summary>    
        [Required]
        [Display(Name = "Номер пары в расписании", Order = 1)]
        [Range(1, 8, ErrorMessage = "Недопустимое значение")]
        public int Number { get; set; }

        /// <summary>
        /// Группа, у которой будет пара
        /// </summary> 
        [ScaffoldColumn(false)]
        public virtual ICollection<Group> Groups { get; set; }

        [ScaffoldColumn(false)]
        public List<int> GroupIds { get; set; }

        [Display(Name = "Группы", Order = 70)]
        [UIHint("MultipleDropDownList")]
        [TargetProperty("GroupIds")]
        [NotMapped]
        public IEnumerable<SelectListItem> GroupDictionary
        {
            get
            {
                var db = new TimetableContext();
                var query = db.Groups;

                if (query != null)
                {
                    var Ids = query.Where(s => s.Lessons.Any(ss => ss.Id == Id)).Select(s => s.Id).ToList();
                    var dictionary = new List<SelectListItem>();
                    dictionary.AddRange(query.ToSelectList(c => c.Id, c => $"{c.GroupName}", c => Ids.Contains(c.Id)));
                    return dictionary;
                }

                return new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } };
            }
        }

        /// <summary>
        /// Преподаватель
        /// </summary> 
        [ScaffoldColumn(false)]
        public int TeacherId { get; set; }
        [ScaffoldColumn(false)]
        public virtual Teacher Teacher { get; set; }
        [Display(Name = "Преподаватель", Order = 50)]
        [UIHint("DropDownList")]
        [TargetProperty("TeacherId")]
        [NotMapped]
        public IEnumerable<SelectListItem> TeacherDictionary
        {
            get
            {
                var db = new TimetableContext();
                var query = db.Teachers;

                if (query != null)
                {
                    var dictionary = new List<SelectListItem>();
                    dictionary.AddRange(query.OrderBy(d => d.Name).ToSelectList(c => c.Id, c => c.Name, c => c.Id == TeacherId));
                    return dictionary;
                }

                return new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } };
            }
        }

        /// <summary>
        /// Дисциплина
        /// </summary> 
        [ScaffoldColumn(false)]
        public int DisciplineId { get; set; }
        [ScaffoldColumn(false)]
        public virtual Discipline Discipline { get; set; }
        [Display(Name = "Дисциплина", Order = 2)]
        [UIHint("RadioList")]
        [TargetProperty("DisciplineId")]
        [NotMapped]
        public IEnumerable<SelectListItem> DisciplineDictionary
        {
            get
            {
                var db = new TimetableContext();
                var query = db.Disciplines;

                if (query != null)
                {
                    var dictionary = new List<SelectListItem>();
                    dictionary.AddRange(query.OrderBy(d => d.Name).ToSelectList(c => c.Id, c => c.Name, c => c.Id == DisciplineId));
                    return dictionary;
                }

                return new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } };
            }
        }





    }
}

web-app-asp-net-mvc-export-xml/Controllers/DisciplinesController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using web_app_asp_net_mvc_export_xml.Models;

namespace web_app_asp_net_mvc_export_xml.Controllers
{
    public class DisciplinesController : Controller
    {
        private readonly string _key = "123456Qq";

        [HttpGet]
        public ActionResult Index()
        {
            var db = new TimetableContext();
            var disciplines = db.Disciplines.ToList();

            return View(disciplines);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var discipline = new Discipline();
            return View(discipline);
        }

        [HttpPost]
        public ActionResult Create(Discipline model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var db = new TimetableContext();
            if (model.Key != _key)
                ModelState.AddModelError("Key", "Ключ для создания/изменения записи указан не верно");
            if (!ModelState.IsValid)
                return View(model);
            db.Disciplines.Add(model);
            db.SaveChanges();

            return RedirectPermanent("/Disciplines/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var db = new TimetableContext();
            var discipline = db.Disciplines.FirstOrDefault(x => x.Id == id);
            if (discipline == null)
                return RedirectPermanent("/Disciplines/Index");

            db.Disciplines.Remove(discipline);
            db.SaveChanges();

            return RedirectPermanent("/Disciplines/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new TimetableContext();
            var discipline = db.Disciplines.FirstOrDefault(x => x.Id == id);
            if (discipline == null)
                return RedirectPermanent("/Disciplines/Index");

            return View(discipline);
        }

        [HttpPost]
        public ActionResult Edit(Discipline model)
        {
            var db = new TimetableContext();
            var discipline = db.Disciplines.FirstOrDefault(x => x.Id == model.Id);
            if (discipline == null)
                ModelState.AddModelError("Id", "Дисциплина не найдена");
            if (model.Key != _key)
                ModelState.AddModelError("Key", "Ключ для создания/изменения записи указан не верно");
            if (!ModelState.IsValid)
                return View(model);

            MappingDiscipline(model, discipline, db);

            db.Entry(discipline).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectPermanent("/Disciplines/Index");
        }

        private void MappingDiscipline(Discipline sourse, Discipline destination, TimetableContext db)
        {
            destination.Name = sourse.Name;
            destination.DisciplineGoal = sourse.DisciplineGoal;
            destination.DisciplineObjectives = sourse.DisciplineObjectives;
            destination.MainSections = sourse.MainSections;
            destination.Key = sourse.Key;


        }

    }
}

web-app-asp-net-mvc-export-xml/Controllers/LessonsController.cs
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Xml.Serialization;
using web_app_asp_net_mvc_export_xml.Models;
using web_app_asp_net_mvc_export_xml.Models.Xml;
using System.Xml;

namespace web_app_asp_net_mvc_export_xml.Controllers
{
    public class LessonsController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var db = new TimetableContext();
            var lessons = db.Lessons.ToList();

            return View(lessons);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var lesson = new Lesson();
            return View(lesson);
        }

        [HttpPost]
        public ActionResult Create(Lesson model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var db = new TimetableContext();

            if (model.GroupIds != null && model.GroupIds.Any())
            {
                var group = db.Groups.Where(s => model.GroupIds.Contains(s.Id)).ToList();
                model.Groups = group;
            }

            db.Lessons.Add(model);
            db.SaveChanges();

            return RedirectPermanent("/Lessons/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var db = new TimetableContext();
            var lesson = db.Lessons.FirstOrDefault(x => x.Id == id);
            if (lesson == null)
                return RedirectPermanent("/Lessons/Index");

            db.Lessons.Remove(lesson);
            db.SaveChanges();

            return RedirectPermanent("/Lessons/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new TimetableContext();
            var lesson = db.Lessons.FirstOrDefault(x => x.Id == id);
            if (lesson == null)
                return RedirectPermanent("/Lessons/Index");

            return View(lesson);
        }

        [HttpPost]
        public ActionResult Edit(Lesson model)
        {
            var db = new TimetableContext();
            var lesson = db.Lessons.FirstOrDefault(x => x.Id == model.Id);
            if (lesson == null)
                ModelState.AddModelError("Id", "Пара не найдена");

            if (!ModelState.IsValid)
                return View(model);

            MappingLesson(model, lesson, db);

            db.Entry(lesson).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectPermanent("/Lessons/Index");
        }

        private void MappingLesson(Lesson sourse, Lesson destination, TimetableContext db)
        {
            destination.Number = sourse.Number;
            destination.DisciplineId = sourse.DisciplineId;
            destination.Discipline = sourse.Discipline;
            destination.TeacherId = sourse.TeacherId;
            destination.Teacher = sourse.Teacher;



            if (destination.Groups != null)
                destination.Groups.Clear();

            if (sourse.GroupIds != null && sourse.GroupIds.Any())
                destination.Groups = db.Groups.Where(s => sourse.GroupIds.Contains(s.Id)).ToList();
        }

        [HttpGet]
        public ActionResult GetImage(int id)
        {
            var db = new TimetableContext();
            var image = db.TeacherImages.FirstOrDefault(x => x.Id == id);
            if (image == null)
            {
                FileStream fs = System.IO.File.OpenRead(Server.MapPath(@"~/Content/Images/not-foto.png"));
                byte[] fileData = new byte[fs.Length];
                fs.Read(fileData, 0, (int)fs.Length);
                fs.Close();

                return File(new MemoryStream(fileData), "image/jpeg");
            }

            return File(new MemoryStream(image.Data), image.ContentType);
        }

        [HttpGet]
        public ActionResult Detail(int id)
        {
            var db = new TimetableContext();
            var lesson = db.Lessons.FirstOrDefault(x => x.Id == id);
            if (lesson == null)
                return RedirectPermanent("/Lessons/Index");

            return View(lesson);
        }

        [HttpGet]
        public ActionResult GetXml()
        {
            var db = new TimetableContext();
            var lessons = db.Lessons.ToList().Select(x => new XmlLesson()
            {
                Number = x.Number,
                TeacherId = x.TeacherId,
                DisciplineId = x.DisciplineId,
               Groups = x.Groups.Select(y => new XmlGroup() { Id = y.Id }).ToList()
            }).ToList();

            XmlSerializer xml = new XmlSerializer(typeof(List<XmlLesson>));
            var ns = new XmlSerializerNamespaces(new[] { XmlQualifiedName.Empty });
            var ms = new MemoryStream();
            xml.Serialize(ms, lessons, ns);
            ms.Position = 0;

            return File(new MemoryStream(ms.ToArray()), "text/xml");
        }
    }
}

web-app-asp-net-mvc-export-xml/Views/Lessons/Create.cshtml
@using web_app_asp_net_mvc_export_xml.Models
@model Lesson

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Create", "Lessons", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.EditorForModel()
        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Lessons", null, new { @class = "btn btn-danger" })
        
    }
</fieldset>

web-app-asp-net-mvc-export-xml/Views/Lessons/Detail.cshtml
@using web_app_asp_net_mvc_export_xml.Models
@model Lesson


<table class="table align-middle " style="text-align:center">
    <tbody>
        <tr>

            <td>
                <br />
                <h1><u>@Model.Discipline.Name</u></h1>
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <h3>Аннотация</h3>
            </td>
        </tr>
    </tbody>
</table>

<div class="row">
    <div class="accordion ">
        <div class="accordion-item" style="background-color: #ffc107;">
            <h2 class="accordion-header" id="one">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse" aria-expanded="false" aria-controls="flush-collapse">
                    Цель дисциплины
                </button>
            </h2>
            <div id="flush-collapse" class="accordion-collapse collapse" aria-labelledby="one">
                <div class="accordion-body">
                    <span><pre style="width: auto; white-space: pre-wrap;">@Model.Discipline.DisciplineGoal</pre></span>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="accordion ">
        <div class="accordion-item" style="background-color: #ffc107;">
            <h2 class="accordion-header" id="two">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse2" aria-expanded="false" aria-controls="flush-collapse2">
                    Задачи дисциплины
                </button>
            </h2>
            <div id="flush-collapse2" class="accordion-collapse collapse" aria-labelledby="two">
                <div class="accordion-body">
                    <span><pre style="width: auto; white-space: pre-wrap;">@Model.Discipline.DisciplineObjectives</pre></span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="accordion ">
        <div class="accordion-item" style="background-color: #ffc107;">
            <h2 class="accordion-header" id="three">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse3" aria-expanded="false" aria-controls="flush-collapse3">
                    Разделы дисциплины
                </button>
            </h2>
            <div id="flush-collapse3" class="accordion-collapse collapse" aria-labelledby="three">
                <div class="accordion-body">
                    <span><pre style="width: auto; white-space: pre-wrap;">@Model.Discipline.MainSections</pre></span>
                </div>
            </div>
        </div>
    </div>
</div>

<br />
@Html.ActionLink("На главную", "Index", "Lessons", null, new { @class = "btn btn-outline-dark" })

@Html.ActionLink("Изменить дисциплины", "Index", "Disciplines", null, new { @class = "btn btn-outline-dark" })


<hr />


<sub><i>Описание может быть не точным</i></sub>

web-app-asp-net-mvc-export-xml/Views/Lessons/Edit.cshtml
@using web_app_asp_net_mvc_export_xml.Models
@model Lesson

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Edit", "Lessons", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary()
        @Html.EditorForModel()
        
        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Lessons", null, new { @class = "btn btn-danger" })
    }
</fieldset>

web-app-asp-net-mvc-export-xml/Views/Lessons/Index.cshtml
@using web_app_asp_net_mvc_export_xml.Models
@using web_app_asp_net_mvc_export_xml.Extensions
@model List<Lesson>

@{
    string controllerName = "Lessons";
}
<br>
<h1><b>Расписание</b></h1>

<br>

<table class="table table-hover table-bordered border-dark  align-middle " style="text-align:center">
    <thead>
        <tr class="bg-secondary">
            <th>
                Номер пары
            </th>
            <th>
                Дисциплина
            </th>
            <th>
                Группа(ы)
            </th>
            <th>
                Преподаватель
            </th>
            <th>
                Фото преподавателя
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var lesson in Model)
        {
            <tr>
                <td>
                    @lesson.Number
                </td>
                <td>
                    <a href="/Lessons/Detail/@lesson.Id">@lesson.Discipline.Name</a>

                </td>
                <td>
                    @string.Join(", ", lesson.Groups.Select(x => $"{x.GroupName}"))
                </td>
                <td>
                    @lesson.Teacher.Name
                </td>
                <td>
                    <img src="/Teachers/GetImage/@lesson.TeacherId" class="rounded" style="max-width: 50px; max-height: 100px;" />
                </td>
                <td>
                    <div class="btn-group mb-3, vertical-align:middle align-middle">
                        <a href="/@controllerName/Edit/@lesson.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                            </svg>
                        </a>
                        <a href="/@controllerName/Delete/@lesson.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-backspace-fill" viewBox="0 0 16 16">
                                <path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z" />
                            </svg>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<br>
<div class="btn-create" style="display: flex; justify-content: flex-end;">
    @Html.ActionLink("Добавить запись", "Create", controllerName, null, new { @class = "btn btn-outline-dark" })
    @Html.ActionLink("XML", "GetXml", controllerName, null, new { @class = "btn btn-outline-dark", @target = "_blank", style = "margin: 0px 15px 0px 15px;" })
</div>
<div class="btn-create" style="display: flex; justify-content: flex-end;">
    <a href="/ImportXmlLessons" class = "btn btn-outline-dark" style = "margin: 20px 15px 0px 15px;">Импорт данных XML</a>
</div>


<br>
<br>
<br>
<br>
<br>
<hr>
<footer>
    <dl>
        <dt>Дополнительная информация:</dt>
    </dl>
    <ol type="I">
        <li><h6><i>Данная работа сделана в ознакомительных целях</i></h6></li>
        <li><h6><i>Все люди вымышлены, а совпадения случайны</i></h6></li>
    </ol>

</footer>