web-app-asp-net-mvc-export-xml/Models/Entities/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web_app_asp_net_mvc_export_xml.Extensions;
using web_app_asp_net_mvc_export_xml.Models.Attributes;
using web_app_asp_net_mvc_export_xml.Models.Enums;

namespace web_app_asp_net_mvc_export_xml.Models
{
    public class Teacher
    {
        ///<summary>
        /// Id
        /// </summary> 
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        ///<summary>
        /// Имя преподавателя
        /// </summary> 
        [Required]
        [Display(Name = "Преподаватель", Order = 5)]
        public string Name { get; set; }

        /// <summary>
        /// Фото преподавателя
        /// </summary> 
        [ScaffoldColumn(false)]
        public virtual TeacherImage TeacherImage { get; set; }

        [Display(Name = "Фото преподавателя", Order = 6)]
        [NotMapped]
        public HttpPostedFileBase TeacherImageFile { get; set; }




        /// <summary>
        /// Пол
        /// </summary> 
        [ScaffoldColumn(false)]
        public Sex Sex { get; set; }

        [Display(Name = "Пол", Order = 7)]
        [UIHint("DropDownList")]
        [TargetProperty("Sex")]
        [NotMapped]
        public IEnumerable<SelectListItem> SexDictionary
        {
            get
            {
                var dictionary = new List<SelectListItem>();

                foreach (Sex type in Enum.GetValues(typeof(Sex)))
                {
                    dictionary.Add(new SelectListItem
                    {
                        Value = ((int)type).ToString(),
                        Text = type.GetDisplayValue(),
                        Selected = type == Sex
                    });
                }

                return dictionary;
            }
        }



        /// <summary>
        /// Должность
        /// </summary> 
        [ScaffoldColumn(false)]
        public Position Position { get; set; }

        [Display(Name = "Должность", Order = 7)]
        [UIHint("RadioList")]
        [TargetProperty("Position")]
        [NotMapped]
        public IEnumerable<SelectListItem> PositionDictionary
        {
            get
            {
                var dictionary = new List<SelectListItem>();

                foreach (Position type in Enum.GetValues(typeof(Position)))
                {
                    dictionary.Add(new SelectListItem
                    {
                        Value = ((int)type).ToString(),
                        Text = type.GetDisplayValue(),
                        Selected = type == Position
                    });
                }

                return dictionary;
            }
        }


        ///<summary>
        /// Список предметов, которые ведет преподаватель
        /// </summary> 
        [ScaffoldColumn(false)]
        public virtual ICollection<Lesson> Lessons { get; set; }
    }
}

web-app-asp-net-mvc-export-xml/Controllers/TeachersController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using web_app_asp_net_mvc_export_xml.Models;

namespace web_app_asp_net_mvc_export_xml.Controllers
{
    public class TeachersController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var db = new TimetableContext();
            var teachers = db.Teachers.ToList();

            return View(teachers);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var teacher = new Teacher();
            return View(teacher);
        }

        [HttpPost]
        public ActionResult Create(Teacher model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var db = new TimetableContext();

            if (model.TeacherImageFile != null)
            {
                var data = new byte[model.TeacherImageFile.ContentLength];
                model.TeacherImageFile.InputStream.Read(data, 0, model.TeacherImageFile.ContentLength);

                model.TeacherImage = new TeacherImage()
                {
                    Guid = Guid.NewGuid(),
                    DateChanged = DateTime.Now,
                    Data = data,
                    ContentType = model.TeacherImageFile.ContentType,
                    FileName = model.TeacherImageFile.FileName
                };
            }


            db.Teachers.Add(model);
            db.SaveChanges();

            return RedirectPermanent("/Teachers/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var db = new TimetableContext();
            var teacher = db.Teachers.FirstOrDefault(x => x.Id == id);
            if (teacher == null)
                return RedirectPermanent("/Teachers/Index");

            db.Teachers.Remove(teacher);
            db.SaveChanges();

            return RedirectPermanent("/Teachers/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new TimetableContext();
            var teacher = db.Teachers.FirstOrDefault(x => x.Id == id);
            if (teacher == null)
                return RedirectPermanent("/Teachers/Index");

            return View(teacher);
        }

        [HttpPost]
        public ActionResult Edit(Teacher model)
        {
            var db = new TimetableContext();
            var teacher = db.Teachers.FirstOrDefault(x => x.Id == model.Id);
            if (teacher == null)
                ModelState.AddModelError("Id", "Преподаватель не найден");

            if (!ModelState.IsValid)
                return View(model);

            MappingTeacher(model, teacher, db);

            db.Entry(teacher).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectPermanent("/Teachers/Index");
        }

        private void MappingTeacher(Teacher sourse, Teacher destination, TimetableContext db)
        {
            destination.Name = sourse.Name;
            destination.Sex = sourse.Sex;
            destination.Position = sourse.Position;

            if (sourse.TeacherImageFile != null)
            {
                var image = db.TeacherImages.FirstOrDefault(x => x.Id == sourse.Id);
                if (image != null)
                    db.TeacherImages.Remove(image);

                var data = new byte[sourse.TeacherImageFile.ContentLength];
                sourse.TeacherImageFile.InputStream.Read(data, 0, sourse.TeacherImageFile.ContentLength);

                destination.TeacherImage = new TeacherImage()
                {
                    Guid = Guid.NewGuid(),
                    DateChanged = DateTime.Now,
                    Data = data,
                    ContentType = sourse.TeacherImageFile.ContentType,
                    FileName = sourse.TeacherImageFile.FileName
                };
            }

        }

        [HttpGet]
        public ActionResult GetImage(int id)
        {
            var db = new TimetableContext();
            var image = db.TeacherImages.FirstOrDefault(x => x.Id == id);
            if (image == null)
            {
                FileStream fs = System.IO.File.OpenRead(Server.MapPath(@"~/Content/Images/not-foto.png"));
                byte[] fileData = new byte[fs.Length];
                fs.Read(fileData, 0, (int)fs.Length);
                fs.Close();

                return File(new MemoryStream(fileData), "image/jpeg");
            }

            return File(new MemoryStream(image.Data), image.ContentType);
        }
    }
}

web-app-asp-net-mvc-export-xml/Views/Teachers/Create.cshtml
@using web_app_asp_net_mvc_export_xml.Models
@model Teacher

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Create", "Teachers", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.EditorForModel()

        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Teachers", null, new { @class = "btn btn-danger" })
    }
</fieldset>

web-app-asp-net-mvc-export-xml/Views/Teachers/Edit.cshtml
@using web_app_asp_net_mvc_export_xml.Models
@model Teacher

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Edit", "Teachers", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary()
        @Html.EditorForModel()

        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Teachers", null, new { @class = "btn btn-danger" })
    }
    
</fieldset>

web-app-asp-net-mvc-export-xml/Views/Teachers/Index.cshtml
@using web_app_asp_net_mvc_export_xml.Models
@using web_app_asp_net_mvc_export_xml.Extensions
@model List<Teacher>

@{
    string controllerName = "Teachers";
}
<br>
<h1><b>Преподаватели </b></h1>
<br>

<table class="table table-hover table-bordered border-dark  align-middle " style="text-align:center">
    <thead>
        <tr class="bg-secondary">
            <th>
                Преподаватель
            </th>
            <th>
                Пол
            </th>
            <th>
                Должность(и)
            </th>
            <th>
                Фото преподавателя
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var teacher in Model)
        {
            <tr>
                <td>
                    @teacher.Name
                </td>
                <td>
                    @teacher.Sex.GetDisplayValue()
                </td>
                <td>
                    @teacher.Position.GetDisplayValue()
                </td>
                <td>
                    <img src="/Teachers/GetImage/@teacher.Id" class="rounded" style="max-width: 100px; max-height: 200px;" />
                </td>
                <td>
                    <div class="btn-group mb-3, vertical-align:middle align-middle">
                        <a href="/@controllerName/Edit/@teacher.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                            </svg>
                        </a>
                        <a href="/@controllerName/Delete/@teacher.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-backspace-fill" viewBox="0 0 16 16">
                                <path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z" />
                            </svg>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
<div class="btn-create">
    @Html.ActionLink("Добавить запись", "Create", controllerName, null, new { @class = "btn btn-outline-dark" })
</div>