web-app-asp-net-mvc-export-xml/Models/Entities/Nationality.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace web_app_asp_net_mvc_export_xml.Models
{
    public class Nationality
    {
        /// <summary>
        /// Id
        /// </summary> 
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Название
        /// </summary>    
        [Required]
        [Display(Name = "Название", Order = 5)]
        public string Name { get; set; }

        /// <summary>
        /// Список книг
        /// </summary> 
        [ScaffoldColumn(false)]
        public virtual ICollection<Group> Groups { get; set; }
    }
}

web-app-asp-net-mvc-export-xml/Controllers/NationalitysController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web_app_asp_net_mvc_export_xml.Models;

namespace web_app_asp_net_mvc_export_xml.Controllers
{
    public class NationalitysController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var db = new TimetableContext();
            var nationalitys = db.Nationalitys.ToList();

            return View(nationalitys);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var nationality = new Nationality();
            return View(nationality);
        }

        [HttpPost]
        public ActionResult Create(Nationality model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var db = new TimetableContext();

            db.Nationalitys.Add(model);
            db.SaveChanges();

            return RedirectPermanent("/Nationalitys/Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var db = new TimetableContext();
            var nationality = db.Nationalitys.FirstOrDefault(x => x.Id == id);
            if (nationality == null)
                return RedirectPermanent("/Nationalitys/Index");

            db.Nationalitys.Remove(nationality);
            db.SaveChanges();

            return RedirectPermanent("/Nationalitys/Index");
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new TimetableContext();
            var nationality = db.Nationalitys.FirstOrDefault(x => x.Id == id);
            if (nationality == null)
                return RedirectPermanent("/Nationalitys/Index");

            return View(nationality);
        }

        [HttpPost]
        public ActionResult Edit(Nationality model)
        {
            var db = new TimetableContext();
            var nationality = db.Nationalitys.FirstOrDefault(x => x.Id == model.Id);
            if (nationality == null)
                ModelState.AddModelError("Id", "Национальность не найден");

            if (!ModelState.IsValid)
                return View(model);

            MappingNationality(model, nationality);

            db.Entry(nationality).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectPermanent("/Nationalitys/Index");
        }

        private void MappingNationality(Nationality sourse, Nationality destination)
        {
            destination.Name = sourse.Name;
        }
    }
}

web-app-asp-net-mvc-export-xml/Views/Nationalitys/Create.cshtml
@using web_app_asp_net_mvc_export_xml.Models
@model Nationality

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Create", "Nationalitys", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.EditorForModel()

        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Nationalitys", null, new { @class = "btn btn-danger" })
    }
</fieldset>

web-app-asp-net-mvc-export-xml/Views/Nationalitys/Edit.cshtml
@using web_app_asp_net_mvc_export_xml.Models
@model Nationality

<fieldset>
    <legend>Пожалуйста, заполните необходимые поля</legend>
    @using (Html.BeginForm("Edit", "Nationalitys", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary()
        @Html.EditorForModel()

        <input type="submit" value="Сохранить" class="btn btn-secondary" />
        @Html.ActionLink("Отменить", "Index", "Nationalitys", null, new { @class = "btn btn-danger" })
    }
    
</fieldset>

web-app-asp-net-mvc-export-xml/Views/Nationalitys/Index.cshtml
@using web_app_asp_net_mvc_export_xml.Models
@using web_app_asp_net_mvc_export_xml.Extensions
@model List<Nationality>

@{
    string controllerName = "Nationalitys";
}
<br>
<h1><b>Национальности</b></h1>
<br>

<table class="table table-hover table-bordered border-dark  align-middle " style="text-align:center">
    <thead>
        <tr class="bg-secondary">
            <th>
                Национальность
            </th>
            <th>
                Действия
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var nationality in Model)
        {
            <tr>
                <td>
                    @nationality.Name
                </td>
                <td>
                    <div class="btn-group mb-3, vertical-align:middle align-middle">
                        <a href="/@controllerName/Edit/@nationality.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                            </svg>
                        </a>
                        <a href="/@controllerName/Delete/@nationality.Id" class="btn btn-outline-dark">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-backspace-fill" viewBox="0 0 16 16">
                                <path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z" />
                            </svg>
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
<div class="btn-create">
    @Html.ActionLink("Добавить запись", "Create", controllerName, null, new { @class = "btn btn-outline-dark" })
</div>